DOMAIN = "notifier_hub"

CONF_PERSONAL_ASSISTANT = "personal_assistant"
CONF_PERSONS = "persons"
CONF_NOTIFY_SERVICES = "notify_services"
CONF_ALEXA_PLAYERS = "alexa_players"
CONF_GOOGLE_PLAYERS = "google_players"
CONF_GOOGLE_TTS_SERVICE = "google_tts_service"
CONF_GOOGLE_NOTIFY_SERVICE = "google_notify_service"
CONF_SIP_SERVER_NAME = "sip_server_name"
CONF_DEFAULT_LANGUAGE = "default_language"
CONF_DEFAULT_VOLUME = "default_volume"
CONF_TTS_WAIT_TIME = "tts_wait_time"
CONF_DEBUG = "debug"
CONF_TEXT_NOTIFICATIONS = "text_notifications"
CONF_SCREEN_NOTIFICATIONS = "screen_notifications"
CONF_SPEECH_NOTIFICATIONS = "speech_notifications"
CONF_ALEXA_NOTIFICATIONS = "alexa_notifications"
CONF_GOOGLE_NOTIFICATIONS = "google_notifications"
CONF_PHONE_NOTIFICATIONS = "phone_notifications"

DEFAULT_PERSONAL_ASSISTANT = "Assistant"
DEFAULT_SIP_SERVER_NAME = "fritz.box:5060"
DEFAULT_LANGUAGE = "es-ES"
DEFAULT_VOLUME = 0.30
DEFAULT_TTS_WAIT_TIME = 3.0
DEFAULT_GOOGLE_TTS_SERVICE = "google_translate_say"
DEFAULT_GOOGLE_NOTIFY_SERVICE = "google_assistant"
DEFAULT_HA_SIP_ADDON = "c7744bff_ha-sip"

SERVICE_SEND = "send"
SERVICE_SET_CONFIG = "set_config"
EVENT_NOTIFIER = "notifier"
