alias: "ALARMA: Avisar si la puerta está abierta"
description: ""
triggers:
  - trigger: state
    entity_id: binary_sensor.front_door_contact
    to: "on"
    for:
      seconds: 5
conditions: []
actions:
  - repeat:
      while:
        - condition: state
          entity_id: binary_sensor.front_door_contact
          state: "on"
      sequence:
        - action: notifier_hub.send
          metadata: {}
          data:
            title: ⭐ Jarvis Alarma.
            message: La puerta está abierta
            notify: true
            location: home
            no_show: false
            priority: false
            alexa: true
            phone: false
        - wait_for_trigger:
            - trigger: state
              entity_id: binary_sensor.front_door_contact
              to: "off"
          timeout: "00:00:30"
mode: single
