alias: ZONES - in/out
description: ""
mode: parallel
max: 4
triggers:
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.train_station
    event: enter
    trigger: zone
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.train_station
    event: leave
    trigger: zone
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.office
    event: enter
    trigger: zone
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.office
    event: leave
    trigger: zone
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.home
    event: enter
    trigger: zone
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.home
    event: leave
    trigger: zone
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.secondary_station
    event: enter
    trigger: zone
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.secondary_station
    event: leave
    trigger: zone
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.family_home
    event: enter
    trigger: zone
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.family_home
    event: leave
    trigger: zone
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.secondary_home
    event: enter
    trigger: zone
  - entity_id:
      - person.person_1
      - person.person_2
    zone: zone.secondary_home
    event: leave
    trigger: zone
conditions:
  - condition: or
    conditions:
      - condition: zone
        entity_id: person.person_1
        zone: zone.home
      - condition: zone
        entity_id: person.person_2
        zone: zone.home
    enabled: false
actions:
  - action: notifier_hub.send
    metadata: {}
    data:
      title: ⭐ Jarvis Presence.
      message: >-
        {{ trigger.to_state.attributes.friendly_name }} {% if trigger.event ==
        'enter' %}arrived at{% else %}left{% endif %} {{
        trigger.zone.attributes.friendly_name }}
      notify: true
      location: home
      no_show: false
      alexa: true
      phone: false
